### ISSUE TITLE
toleration list?

### ISSUE THREAD

**Issue by jeremyeder** [openshift/cluster-nfd-operator#4]
https://github.com/openshift/cluster-nfd-operator/blob/01743d351014084d4d33e6c35d9fdff30b2cf273/assets/worker/0700_worker_daemonset.yaml#L17

This pod must tolerate any taint.  For example, the SDN pod has this list:

```
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300

```
